find_trending_companies:
  description: >
    Encontrar las principales empresas en tendencia en las noticias en {sector} buscando las últimas noticias. Encontrar nuevas empresas que no hayas encontrado antes.
  expected_output: >
    Una lista de empresas en tendencia en {sector}
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Dada una lista de empresas en tendencia, proporcionar un análisis detallado de cada empresa en un informe buscando en línea
  expected_output: >
    Un informe que contenga un análisis detallado de cada empresa
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    Analizar los hallazgos de la investigación y seleccionar la mejor empresa para inversión.
    Enviar una notificación push al usuario con la decisión y una frase de justificación.
    Luego responder con un informe detallado sobre por qué se eligió esta empresa y cuáles no fueron seleccionadas.
  expected_output: >
    La empresa elegida y por qué fue elegida; las empresas que no fueron seleccionadas y por qué no fueron seleccionadas.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
