research_task:
  description: >
    Realiza una investigación exhaustiva sobre la empresa {company}. Enfócate en:
    1. Estado y salud actual de la empresa
    2. Rendimiento histórico de la empresa
    3. Principales desafíos y oportunidades
    4. Noticias y eventos recientes
    5. Perspectivas futuras y desarrollos potenciales

    Asegúrate de organizar tus hallazgos en un formato estructurado con secciones claras.
  expected_output: >
    Un documento de investigación completo con secciones bien organizadas que cubran
    todos los aspectos solicitados de {company}. Incluye hechos específicos, cifras
    y ejemplos cuando sea relevante.
  agent: researcher

analysis_task:
  description: >
    Analiza los hallazgos de la investigación y crea un informe completo sobre {company}.
    Tu informe debe:
    1. Comenzar con un resumen ejecutivo
    2. Incluir toda la información clave de la investigación
    3. Proporcionar un análisis perspicaz de tendencias y patrones
    4. Ofrecer una perspectiva de mercado para la empresa, señalando que esto no debe usarse para decisiones de trading
    5. Estar formateado en un estilo profesional, fácil de leer, con encabezados claros
  expected_output: >
    Un informe pulido y profesional en español sobre {company} que presente los hallazgos de la investigación con análisis e ideas adicionales.
    El informe debe estar bien estructurado con un resumen ejecutivo, secciones principales y conclusión.
  agent: analyst
  context:
    - research_task # Nos aseguramos que el output de la tarea analysis_task incluya el output de research_task
  output_file: output/report.md
